// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBZgXl7vfioIp5yt3--fLWzcgR1i7cdU0',
    appId: '1:442886533884:web:aa741840faa33375031d79',
    messagingSenderId: '442886533884',
    projectId: 'abastecimento-273bb',
    authDomain: 'abastecimento-273bb.firebaseapp.com',
    storageBucket: 'abastecimento-273bb.firebasestorage.app',
    measurementId: 'G-77QPZDWN7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAILFFMCMnnQI7J1ULv9oAACxfujlOZZlw',
    appId: '1:442886533884:android:560f56aa60761e5f031d79',
    messagingSenderId: '442886533884',
    projectId: 'abastecimento-273bb',
    storageBucket: 'abastecimento-273bb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBZgXl7vfioIp5yt3--fLWzcgR1i7cdU0',
    appId: '1:442886533884:web:40c46119029c0eec031d79',
    messagingSenderId: '442886533884',
    projectId: 'abastecimento-273bb',
    authDomain: 'abastecimento-273bb.firebaseapp.com',
    storageBucket: 'abastecimento-273bb.firebasestorage.app',
    measurementId: 'G-W1SPKFT1PS',
  );

}